### ISSUE TITLE
Research filesystem handling and create PoC

### ISSUE THREAD

**Issue by francium** [BigBlockDataChain/docs#4]
Things to research

- Programming language to use (C++/C, Rust, Go, NodeJS+JavaScript, something
- Programming language interop with JavaScript/Electron
- Electron's API for filesystem (is it enough, does it provide everything required for filesystem IO and file management?)
- Cross platform compatibility and foreseeable issues

Would be great if a PoC of the filesystem interface could be created to demonstrate feasibility. It doesn't need to be compatible with the frontend yet, it can use a simple CLI interface.

**Comment by KelvinKKLin** [comment]
Preliminary research comments:

1. Programming languages to use
- JavaScript seems to work just fine. Anything else would require us to perhaps set up a backend and make REST API calls, which seems like overkill at this point.
- We may want to investigate faster languages later on if efficiency becomes an issue, but I do not see us having issues using JavaScript for our PoC.

2. Programming language interop with JavaScript/Electron
- Not applicable at this point in time.
- JavaScript and Electron seems to work just fine for the PoC.

3. Electron's API for filesystem
- We can create, read, modify (write), and delete.
- All other functionality associated with files (e.g. tags, links, associations) should be done through our own data structures.
- *TODO*: Figure out if we can also see a list of files, or the file hierarchy.

4. Cross platform compatibility and foreseeable issues
- Further testing should be done on Mac and Linux platforms
- There may be problems in the future if the user has too many files.
- We will need to find a way to detect different file types in order to properly render everything.
